name: Github Action sharing --Greeting

on:
   push

jobs:
   Greeting:
     runs-on: ubuntu-latest
     steps:
      - name: Say hello
        run: echo "${{env.GREETING}} $FULL_NAME . TODAY is ${{env.DAY_OF_WEEK}}"
        env:
          FULL_NAME: 'George Zhao'
     env:
      GREETING: Hello
env:
  DAY_OF_WEEK: Monday