name: Github Action sharing --List

on:
   push

jobs:
   List:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v4
       - name: List
         run: ls -al
       - name: pwd
         run: pwd
     